Repository bounswe574-G3/swe574_2022_repo, pull requests merged in 2022-12, with the labels that each got.

#6 resources module has been added.
  swe573_2022_repo/space/admin.py
  swe573_2022_repo/space/forms/__init__.py
  swe573_2022_repo/space/forms/resource.py
  swe573_2022_repo/space/forms/update_resource.py
  swe573_2022_repo/space/migrations/0002_resourcemodel.py
  swe573_2022_repo/space/models/__init__.py
  swe573_2022_repo/space/models/resource.py
  swe573_2022_repo/space/templates/pages/resource.html
  swe573_2022_repo/space/templates/pages/spacedetails.html
  swe573_2022_repo/space/templates/pages/update-resource.html
  swe573_2022_repo/space/urls.py
  swe573_2022_repo/space/views/__init__.py
  swe573_2022_repo/space/views/delete_resource.py
  swe573_2022_repo/space/views/resource.py
  swe573_2022_repo/space/views/spacedetails.py
  swe573_2022_repo/space/views/update_resource.py
Labels: development

#7 links added for help in questions
  swe573_2022_repo/quiz/migrations/0002_questionmodel_help_link.py
  swe573_2022_repo/quiz/models/question_model.py
  swe573_2022_repo/quiz/templates/attempt_quiz.html
  swe573_2022_repo/quiz/templates/create-question.html
  swe573_2022_repo/quiz/views/attempt_quiz.py
  swe573_2022_repo/quiz/views/create_question.py
Labels: enhancement, development

#9 Annotation
  swe573_2022_repo/Pipfile
  swe573_2022_repo/Pipfile.lock
  swe573_2022_repo/annotator/__init__.py
  swe573_2022_repo/annotator/admin.py
  swe573_2022_repo/annotator/apps.py
  swe573_2022_repo/annotator/filters.py
  swe573_2022_repo/annotator/migrations/0001_initial.py
  swe573_2022_repo/annotator/migrations/0002_alter_annotation_user.py
  swe573_2022_repo/annotator/migrations/0003_alter_annotation_user.py
  swe573_2022_repo/annotator/migrations/0004_alter_annotation_user.py
  swe573_2022_repo/annotator/migrations/__init__.py
  swe573_2022_repo/annotator/models.py
  swe573_2022_repo/annotator/serializers.py
  swe573_2022_repo/annotator/urls.py
  swe573_2022_repo/annotator/views.py
  swe573_2022_repo/colearning/settings.py
  swe573_2022_repo/colearning/urls.py
  swe573_2022_repo/space/templates/pages/display-resource.html
  swe573_2022_repo/space/templates/pages/homepage.html
  swe573_2022_repo/space/templates/pages/spacedetails.html
  swe573_2022_repo/space/urls.py
  swe573_2022_repo/space/views/__init__.py
  swe573_2022_repo/space/views/display_resource.py
  swe573_2022_repo/static/css/annotator.min.css
  swe573_2022_repo/static/js/annotator.min.js
  swe573_2022_repo/templates/base.html
Labels: enhancement, development

#14 Space details page has been redesign
  swe573_2022_repo/space/forms/create_step.py
  swe573_2022_repo/space/templates/pages/homepage.html
  swe573_2022_repo/space/templates/pages/spacedetails.html
  swe573_2022_repo/space/views/homepage.py
Labels: bug, design

#15 Added sections for homepage and implemented updating quiz feature
  swe573_2022_repo/quiz/templates/quizes.html
  swe573_2022_repo/quiz/templates/update-question.html
  swe573_2022_repo/quiz/urls.py
  swe573_2022_repo/quiz/views/__init__.py
  swe573_2022_repo/quiz/views/update_question.py
  swe573_2022_repo/space/templates/pages/discussionboard.html
  swe573_2022_repo/space/templates/pages/glossarysection.html
  swe573_2022_repo/space/templates/pages/homepage.html
  swe573_2022_repo/space/templates/pages/learningsteps.html
  swe573_2022_repo/space/templates/pages/quizsection.html
  swe573_2022_repo/space/templates/pages/relationgraph.html
  swe573_2022_repo/space/templates/pages/resourcesection.html
  swe573_2022_repo/space/templates/pages/spacedetails.html
  swe573_2022_repo/space/urls.py
  swe573_2022_repo/space/views/__init__.py
  swe573_2022_repo/space/views/discussion_section.py
  swe573_2022_repo/space/views/glossary_section.py
  swe573_2022_repo/space/views/graph_section.py
  swe573_2022_repo/space/views/learning_steps.py
  swe573_2022_repo/space/views/quiz_section.py
  swe573_2022_repo/space/views/resources_section.py
  swe573_2022_repo/templates/base.html
  swe573_2022_repo/templates/components/footer.html
Labels: enhancement, development, design

#17 Add activity stream feature
  swe573_2022_repo/quiz/__init__.py
  swe573_2022_repo/quiz/apps.py
  swe573_2022_repo/space/__init__.py
  swe573_2022_repo/space/apps.py
  swe573_2022_repo/space/migrations/0008_activitystreammodel.py
  swe573_2022_repo/space/models/__init__.py
  swe573_2022_repo/space/models/activitystream.py
  swe573_2022_repo/space/signals.py
  swe573_2022_repo/space/templates/pages/spacedetails.html
  swe573_2022_repo/space/views/spacedetails.py
Labels: enhancement
